# This workflow builds the site/static/ingredients.json file
name: Build ingredients

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - ingredients/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        working-directory: site
        run: |
          pip install --user pipenv
          pipenv sync
      
      - name: Parse ingredients
        working-directory: site
        run: |
          pipenv run scripts/ingredients.py > static/ingredients.json
      
      - name: Commit
        run: |
          timestamp=$(date -u)
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Updated: ${timestamp}" || exit 0
          git push
